#!/usr/bin/env python3
"""
semextract.py — the shared SemDB extraction ENGINE.

All the mechanical plumbing of "run a small model once per corpus item and
materialize the schema's attribute table" lives here and is tested once:
  - vLLM/OpenAI endpoint calls with GUIDED-JSON decoding (schema-valid output)
  - local HuggingFace backends (text LLM / VLM)
  - concurrency for the endpoint path (a vLLM server batches concurrent requests)
  - per-row error tolerance + a systemic-failure guard
  - crash-safe `.partial` checkpoint with atomic promote
  - `<out>.meta.json` instrumentation

The SEMANTIC / corpus-specific decisions are supplied by a small `ExtractDriver`
(prompt construction incl. context columns, column/key mapping, modality
preprocessing). The `Default` driver reproduces the generic behavior; per-corpus
drivers are generated by the Extractor agent and call `run(<their Driver>, ...)`.

Contract of the produced attribute table (one JSON object per item):
  {"<id_col>": ..., <schema attribute columns>, "conf": <float>}
"""

import ast
import csv
import json
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from typing import Protocol


# ---------------------------------------------------------------------------
# Driver interface — the 3 corpus-specific hooks a driver must supply.
# ---------------------------------------------------------------------------

class ExtractDriver(Protocol):
    def map_columns(self, header):
        """header: list[str] of the corpus CSV columns.
        Returns {"id": str, "text": str|None, "image": str|None, "context": list[str]}."""
        ...

    def preprocess(self, row, cols):
        """row: dict of one corpus row; cols: the map_columns() result.
        Returns {"text": str} for text modality OR {"image_path": str} for image."""
        ...

    def build_prompt(self, schema, row, cols):
        """Returns the instruction prompt for this row (may inject context columns)."""
        ...


# ---------------------------------------------------------------------------
# Prompt helpers (also reusable by generated drivers via semextract.build_prompt).
# ---------------------------------------------------------------------------

def entity_attr(schema):
    """The single attribute a weak model should extract in prompt-style 'simple':
    the join key (brand/entity/name), not the boolean/type/alias/conf helpers."""
    attrs = schema.get("attributes", [])
    for a in attrs:
        n = a["name"].lower()
        if re.search(r"entity|brand|name", n) and not re.search(r"type|alias|conf", n):
            return a["name"]
    return attrs[0]["name"] if attrs else "value"


def build_prompt(schema, style="json"):
    """Render schema.attributes into a model prompt. Generated drivers can call this
    and append their own context lines before returning from build_prompt()."""
    attrs = schema.get("attributes", [])
    if style == "simple":
        ent = entity_attr(schema)
        a = next((x for x in attrs if x["name"] == ent), {})
        instr = a.get("extract_instruction", a.get("description", f"the {ent}"))
        return ("Look at the image. " + instr +
                "\nAnswer with ONLY the name (at most a few words). "
                "If there is no logo, answer exactly: none. Do not describe the image.")
    fields, instrs = [], []
    for a in attrs:
        t = a.get("type", "string")
        fields.append(f'"{a["name"]}": <{t}>')
        instrs.append(f'- {a["name"]}: {a.get("extract_instruction", a.get("description",""))}'
                      + (" (use 'none'/[] if not present)" if a.get("allow_none") else ""))
    vocab = ""
    for a in attrs:
        if a.get("vocabulary"):
            vocab += f'\nAllowed values for {a["name"]}: {", ".join(a["vocabulary"])}.'
    schema_line = "{" + ", ".join(fields) + ', "conf": <0.0-1.0>}'
    return (
        "Extract the following fields. Respond with STRICT JSON only, no prose:\n"
        + schema_line + "\n" + "\n".join(instrs) + vocab
    )


# ---------------------------------------------------------------------------
# Parsing (weak-model output salvage + strict-JSON object extraction).
# ---------------------------------------------------------------------------

def _find_json(text):
    """Return the LAST parseable JSON object in the text, or None."""
    blobs, depth, start = [], 0, None
    for i, ch in enumerate(text or ""):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}" and depth > 0:
            depth -= 1
            if depth == 0 and start is not None:
                blobs.append(text[start:i + 1])
                start = None
    for blob in reversed(blobs):
        for candidate in (blob, _repair_json(blob)):
            try:
                o = json.loads(candidate)
                if isinstance(o, dict):
                    return o
            except json.JSONDecodeError:
                pass
        try:
            o = ast.literal_eval(blob)          # tolerate single-quoted dicts
            if isinstance(o, dict):
                return o
        except (ValueError, SyntaxError):
            pass
    return None


def _repair_json(blob):
    """Best-effort repair of the malformations small models emit and that json
    rejects: trailing commas, `0.`/`.5` numbers, and Python True/False/None."""
    b = re.sub(r",(\s*[}\]])", r"\1", blob)             # trailing comma before } or ]
    b = re.sub(r"(?<=[:\s\[,])\.(\d)", r"0.\1", b)      # .5 -> 0.5
    b = re.sub(r"(\d)\.(?=\s*[,}\]])", r"\1.0", b)      # 0.  -> 0.0
    b = re.sub(r"\bTrue\b", "true", b)
    b = re.sub(r"\bFalse\b", "false", b)
    b = re.sub(r"\bNone\b", "null", b)
    return b


def _norm_key(s):
    return re.sub(r"[^a-z0-9]", "", str(s).lower())


def parse_json_object(text, schema):
    """Returns (record, ok). ok=False means no valid JSON was found in the model
    output — i.e. the 'none' is a PARSE FAILURE, not a genuine empty extraction."""
    default = {a["name"]: ([] if "array" in a.get("type", "") or a.get("multi")
                           else "none") for a in schema.get("attributes", [])}
    default["conf"] = 0.0
    obj = _find_json(text)
    if not isinstance(obj, dict):
        return dict(default), False
    norm = {_norm_key(k): v for k, v in obj.items()}
    out = {}
    for a in schema.get("attributes", []):
        v = obj.get(a["name"], norm.get(_norm_key(a["name"]), default[a["name"]]))
        out[a["name"]] = "none" if v is None else v   # JSON null → 'none' sentinel
    out["conf"] = float(obj.get("conf") or norm.get("conf") or norm.get("confidence")
                        or obj.get("logo_conf") or 0.0)
    return out, True


def parse_simple(text, schema):
    """Salvage the entity name from a weak model's prose/dict output."""
    ent = entity_attr(schema)
    t = (text or "").strip()
    skip = {a["name"].lower() for a in schema.get("attributes", [])} | {"true", "false", "none"}
    quotes = [q.strip() for q in re.findall(r"['\"]([^'\"]{1,60})['\"]", t)
              if q.strip().lower() not in skip]
    val = quotes[0] if quotes else (t.splitlines()[0].strip() if t else "")
    val = re.sub(r"^(the logo is( a| an)?|this is( a| an)?|it is( a| an)?|logo:|answer:)\s*",
                 "", val, flags=re.I).strip().strip(".").strip()
    if not val or re.match(r"^(none|no logo|no|n/?a|unknown|not a logo)$", val, re.I) \
            or len(val.split()) > 8:
        val = "none"
    rec = {a["name"]: ([] if "array" in a.get("type", "") else "none")
           for a in schema.get("attributes", [])}
    rec[ent] = val
    rec["conf"] = 0.0 if val == "none" else 0.7
    return rec, True


# ---------------------------------------------------------------------------
# Model backends (loaded lazily so imports work without torch/transformers).
# ---------------------------------------------------------------------------

def _dep_exit(pkgs, e):
    sys.stderr.write(
        f"semextract needs: {pkgs}\n  pip install {pkgs}\n"
        "and network access to huggingface.co for the model weights.\n"
        f"(import error: {e})\n")
    sys.exit(2)


def load_text_model(model_id):
    try:
        import torch  # noqa: F401
        from transformers import AutoModelForCausalLM, AutoTokenizer
    except Exception as e:
        _dep_exit("torch transformers", e)
    tok = AutoTokenizer.from_pretrained(model_id)
    mdl = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype="auto")
    return ("text", tok, mdl)


def _load_vlm_class():
    try:
        from transformers import AutoModelForImageTextToText as VLM
        return VLM
    except ImportError:
        from transformers import AutoModelForVision2Seq as VLM  # older transformers
        return VLM


def load_image_model(model_id):
    try:
        import torch  # noqa: F401
        from transformers import AutoProcessor  # noqa: F401
        from PIL import Image  # noqa: F401
    except Exception as e:
        _dep_exit("torch transformers pillow accelerate", e)
    from transformers import AutoProcessor
    VLM = _load_vlm_class()
    proc = AutoProcessor.from_pretrained(model_id)
    mdl = VLM.from_pretrained(model_id, torch_dtype="auto")
    return ("image", proc, mdl)


# Anti-degeneration decoding — stops the "santa anita park" ×50 repetition collapse.
_GEN = dict(do_sample=False, repetition_penalty=1.3, no_repeat_ngram_size=3)


def gen_text(backend, prompt, max_new_tokens):
    import torch
    _, tok, mdl = backend
    messages = [{"role": "user", "content": prompt}]
    text = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(text, return_tensors="pt").to(mdl.device)
    with torch.no_grad():
        out = mdl.generate(**inputs, max_new_tokens=max_new_tokens, **_GEN)
    return tok.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)


def gen_image(backend, image_path, prompt, max_new_tokens):
    import torch
    from PIL import Image
    _, proc, mdl = backend
    image = Image.open(image_path).convert("RGB")
    messages = [{"role": "user", "content": [{"type": "image"}, {"type": "text", "text": prompt}]}]
    chat = proc.apply_chat_template(messages, add_generation_prompt=True)
    inputs = proc(text=chat, images=[image], return_tensors="pt").to(mdl.device)
    input_len = inputs["input_ids"].shape[1]
    with torch.no_grad():
        out = mdl.generate(**inputs, max_new_tokens=max_new_tokens, **_GEN)
    return proc.batch_decode(out[:, input_len:], skip_special_tokens=True)[0]


def resolve_image_path(uri, image_dir):
    """Resolve an image reference to a real file. Handles: an already-absolute path
    (animals), a path relative to a base — full repo-relative under the sembench root
    (cars/medical) or a bare filename under an images/ dir (mmqa)."""
    uri = str(uri)
    if os.path.isabs(uri) and os.path.exists(uri):
        return uri
    if image_dir:
        for cand in (os.path.join(image_dir, uri), os.path.join(image_dir, os.path.basename(uri))):
            if os.path.exists(cand):
                return cand
    return uri  # last resort: assume the column already holds a usable path


# ---------------------------------------------------------------------------
# vLLM / OpenAI-compatible endpoint backend, with GUIDED JSON decoding.
# ---------------------------------------------------------------------------

def build_json_schema(schema):
    """Turn schema.json attributes into a JSON Schema for guided decoding."""
    props, required = {}, []
    for a in schema.get("attributes", []):
        t = a.get("type", "string").lower()
        if a.get("vocabulary"):
            js = {"type": "string", "enum": list(a["vocabulary"])}
        elif "bool" in t:
            js = {"type": "boolean"}
        elif any(k in t for k in ("float", "double", "number", "real", "int")):
            js = {"type": "number"}
        elif "array" in t or "list" in t:
            js = {"type": "array", "items": {"type": "string"}}
        else:
            js = {"type": "string"}
        if a.get("allow_none") and js.get("type") in ("string", "number", "boolean"):
            js = {"type": [js["type"], "null"], **({"enum": js["enum"]} if "enum" in js else {})}
        props[a["name"]] = js
        required.append(a["name"])
    props["conf"] = {"type": "number"}
    required.append("conf")
    return {"type": "object", "properties": props, "required": required,
            "additionalProperties": False}


def _data_url(path):
    import base64
    ext = (os.path.splitext(path)[1].lstrip(".") or "png").lower()
    mime = "jpeg" if ext in ("jpg", "jpeg") else ext
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    return f"data:image/{mime};base64,{b64}"


@dataclass(frozen=True)
class _Cfg:
    model: str
    endpoint: str
    api_key: str
    max_new_tokens: int
    timeout: int


def gen_endpoint_full(cfg, json_schema, prompt, modality, image_path=None, text=None,
                      logprobs=False, image_paths=None):
    """POST one chat completion to an OpenAI-compatible server with guided_json.
    Returns the whole `choices[0]` object — message plus, when `logprobs=True`, the
    per-token logprobs a caller needs to derive a CALIBRATED confidence (see semvqa).

    `image_paths` attaches several images in order, for predicates that compare two
    rows (a pairwise join condition). `image_path` remains the single-image form."""
    import urllib.request
    content = [{"type": "text", "text": prompt}]
    if modality == "image":
        paths = image_paths if image_paths is not None else [image_path]
        for path in paths:
            content.append({"type": "image_url", "image_url": {"url": _data_url(path)}})
    else:
        content[0]["text"] = prompt + "\n\nINPUT:\n" + (text or "")
    body = {
        "model": cfg.model,
        "messages": [{"role": "user", "content": content}],
        "max_tokens": cfg.max_new_tokens,
        "temperature": 0,
        "guided_json": json_schema,
        "response_format": {"type": "json_schema",
                            "json_schema": {"name": "extract", "schema": json_schema}},
        # Every call here is a structured extraction whose answer is a label, a field
        # value or a boolean — there is nothing to reason about, and on a reasoning
        # model the chain of thought lands INSIDE the JSON `answer` string and eats the
        # token budget. Measured on Qwen3.6-35B-A3B: with thinking on, a yes/no question
        # hits max_tokens at 512 with the JSON still unterminated (at the default 64 the
        # response has no `content` at all, so every oracle label abstains); with
        # thinking off the same question finishes in 35 tokens with clean JSON.
        # Chat templates that do not define this kwarg ignore it.
        "chat_template_kwargs": {"enable_thinking": False},
    }
    if logprobs:
        body["logprobs"] = True
    req = urllib.request.Request(
        cfg.endpoint.rstrip("/") + "/chat/completions",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json",
                 "Authorization": f"Bearer {cfg.api_key}"},
    )
    with urllib.request.urlopen(req, timeout=cfg.timeout) as resp:
        out = json.loads(resp.read())
    return out["choices"][0]


def gen_endpoint(cfg, json_schema, prompt, modality, image_path=None, text=None):
    """The assistant message content (guaranteed schema-valid JSON)."""
    return gen_endpoint_full(cfg, json_schema, prompt, modality,
                             image_path=image_path, text=text)["message"]["content"]


# ---------------------------------------------------------------------------
# Default driver — reproduces the generic (query-agnostic) extraction behavior.
# ---------------------------------------------------------------------------

class Default:
    """Reference driver: generic prompt from schema, explicit column mapping, and
    image-resolve/text-read preprocessing. Generated per-corpus drivers subclass or
    replace these three hooks (e.g. to inject structured context columns)."""

    def __init__(self, id_col, text_col=None, image_col=None, image_dir=None,
                 context_cols=None, style="json"):
        self.id_col = id_col
        self.text_col = text_col
        self.image_col = image_col
        self.image_dir = image_dir
        self.context_cols = context_cols or []
        self.style = style

    def map_columns(self, header):
        return {"id": self.id_col, "text": self.text_col,
                "image": self.image_col, "context": self.context_cols}

    def preprocess(self, row, cols):
        if cols.get("image"):
            uri = row[cols["image"] or cols["id"]]
            return {"image_path": resolve_image_path(uri, self.image_dir)}
        return {"text": row.get(cols["text"] or "text", "")}

    def build_prompt(self, schema, row, cols):
        return build_prompt(schema, self.style)   # generic; no context injection


# ---------------------------------------------------------------------------
# The engine.
# ---------------------------------------------------------------------------

def _none_record(schema, id_col, id_val):
    rec = {a["name"]: ([] if "array" in a.get("type", "") or a.get("multi") else "none")
           for a in schema.get("attributes", [])}
    rec["conf"] = 0.0
    rec[id_col] = id_val
    return rec


def run(driver, schema, table_path, out_path, *, modality, model,
        endpoint=None, api_key="EMPTY", concurrency=8, theta=None,
        image_dir=None, limit=0, max_new_tokens=128, timeout=120,
        prompt_style="json", debug=0):
    """Extract the whole corpus with `driver` and write the attribute table to
    out_path (+ out_path+'.meta.json'). Returns the meta dict.

    Concurrency helps ONLY the endpoint path (a vLLM server batches concurrent
    requests). A local in-process HF model is single-GPU and not thread-safe, so it
    always runs serially. On systemic failure (most calls raised — bad endpoint/
    model/creds) the engine does NOT write out_path and exits non-zero, so the
    caller/orchestrator re-runs rather than caching a broken corpus.

    `image_dir` is a convenience: when given, it is forwarded onto the driver
    (`driver.image_dir`) so a driver whose preprocess() reads `self.image_dir`
    works whether it set that itself or relied on the engine to."""
    if image_dir is not None:
        setattr(driver, "image_dir", image_dir)
    use_endpoint = bool(endpoint)
    style = "json" if use_endpoint else prompt_style
    json_schema = build_json_schema(schema) if use_endpoint else None
    parse = (lambda raw: parse_simple(raw, schema)) if style == "simple" \
        else (lambda raw: parse_json_object(raw, schema))
    primary = entity_attr(schema) if style == "simple" \
        else schema.get("attributes", [{}])[0].get("name")
    if theta is None:
        theta = schema.get("residual", {}).get("theta", 0.5)
    cfg = _Cfg(model=model, endpoint=endpoint or "", api_key=api_key,
               max_new_tokens=max_new_tokens, timeout=timeout)

    t_start = time.time()
    rows = list(csv.DictReader(open(table_path)))
    if limit:
        rows = rows[:limit]
    cols = driver.map_columns(list(rows[0].keys()) if rows else [])
    id_col = cols["id"]

    backend = None
    if not use_endpoint:
        backend = (load_text_model(model) if modality == "text" else load_image_model(model))
    else:
        print(f"[extract] using guided-JSON endpoint {endpoint} (model {model})")

    attrs = [None] * len(rows)
    n_parse_fail = n_none = n_lowconf = n_calls = n_error = 0

    def process_row(i, r):
        """Model call + parse for ONE row. Touches no shared counters (concurrency-safe);
        the main thread tallies in row order."""
        id_val = r[id_col]
        pre = driver.preprocess(r, cols)
        if modality == "image":
            path = pre.get("image_path")
            if not path or not os.path.exists(path):
                return {"i": i, "rec": _none_record(schema, id_col, id_val), "ok": True,
                        "called": False, "missing": path or "(no path)", "error": None, "raw": ""}
        prompt = driver.build_prompt(schema, r, cols)
        try:
            if modality == "text":
                raw = (gen_endpoint(cfg, json_schema, prompt, "text", text=pre.get("text", ""))
                       if use_endpoint else
                       gen_text(backend, prompt + "\n\nINPUT:\n" + pre.get("text", ""), max_new_tokens))
            else:
                raw = (gen_endpoint(cfg, json_schema, prompt, "image", image_path=pre["image_path"])
                       if use_endpoint else
                       gen_image(backend, pre["image_path"], prompt, max_new_tokens))
            rec, ok = parse(raw)          # parse INSIDE the boundary: a malformed but
                                          # returned response must not abort the batch
        except Exception as e:  # noqa: BLE001 — one bad row must not kill the batch
            return {"i": i, "rec": _none_record(schema, id_col, id_val), "ok": False,
                    "called": True, "missing": None, "error": str(e), "raw": ""}
        rec[id_col] = id_val
        return {"i": i, "rec": rec, "ok": ok, "called": True,
                "missing": None, "error": None, "raw": raw}

    def record(res):
        """Single-threaded tally + progress print, called in row order."""
        nonlocal n_parse_fail, n_none, n_lowconf, n_calls, n_error
        i, rec = res["i"], res["rec"]
        attrs[i] = rec
        if res["called"]:
            n_calls += 1
        if res["missing"]:
            n_none += 1
            print(f"[extract] {i+1}/{len(rows)} MISSING IMAGE: {res['missing']}")
            return
        if res["error"]:
            n_parse_fail += 1
            n_error += 1
            print(f"[extract] {i+1}/{len(rows)} {str(rec.get(id_col))[:40]!r} "
                  f"CALL ERROR: {res['error']}")
            return
        if i < debug:
            print(f"[debug row {i}] raw output:\n{res['raw']}\n"
                  f"[debug row {i}] parsed ok={res['ok']} -> {rec}\n")
        val = rec.get(primary)
        if not res["ok"]:
            n_parse_fail += 1
        elif val in (None, "none", "", []):
            n_none += 1
        elif rec["conf"] < theta:
            n_lowconf += 1
        print(f"[extract] {i+1}/{len(rows)} {str(rec.get(id_col))[:40]!r} -> {rec.get(primary)}"
              + ("" if res["ok"] else "  [PARSE-FAIL]"))

    workers = max(1, concurrency) if use_endpoint else 1
    if not use_endpoint and concurrency > 1:
        print(f"[extract] --concurrency {concurrency} ignored for a local model "
              f"(in-process HF model is single-GPU/serial); use an endpoint for concurrency.")
    elif use_endpoint and workers > 1:
        print(f"[extract] dispatching endpoint requests with concurrency={workers}")

    # Checkpoint to a SIDECAR, never straight to out_path — keeps the invariant
    # "out_path exists ⟺ the run completed".
    partial_out = out_path + ".partial"

    def checkpoint():
        json.dump([a for a in attrs if a is not None], open(partial_out, "w"), indent=2)

    done = 0
    if workers > 1:
        with ThreadPoolExecutor(max_workers=workers) as ex:
            for res in ex.map(process_row, range(len(rows)), rows):
                record(res)
                done += 1
                if done % 50 == 0:
                    checkpoint()
    else:
        for i, r in enumerate(rows):
            record(process_row(i, r))
            done += 1
            if done % 50 == 0:
                checkpoint()

    attrs = [a for a in attrs if a is not None]
    elapsed = time.time() - t_start

    if n_calls > 0 and n_error >= max(1, n_calls // 2):
        checkpoint()
        sys.stderr.write(
            f"[extract] ABORT: {n_error}/{n_calls} model calls errored — likely a bad "
            f"endpoint/model/credentials (not a weak model). Not writing {out_path}; "
            f"partial results in {partial_out}.\n")
        sys.exit(3)

    json.dump(attrs, open(out_path, "w"), indent=2)
    if os.path.exists(partial_out):
        os.remove(partial_out)               # promote: out_path is now authoritative
    n_ok = len(attrs) - n_parse_fail - n_none
    meta = {
        "model": model, "endpoint": endpoint, "modality": modality,
        "rows": len(attrs), "extracted": n_ok, "none": n_none,
        "low_conf": n_lowconf, "parse_fail": n_parse_fail,
        "errors": n_error,
        "llm_calls": n_calls,
        "theta": theta,
        "elapsed_sec": round(elapsed, 2),
        "sec_per_row": round(elapsed / max(1, len(attrs)), 3),
        "rows_per_sec": round(len(attrs) / max(1e-9, elapsed), 2),
        "concurrency": workers,
    }
    json.dump(meta, open(out_path + ".meta.json", "w"), indent=2)
    print(f"\n[extract] wrote {len(attrs)} rows -> {out_path}  ({elapsed:.1f}s, {meta['sec_per_row']}s/row)")
    print(f"[extract]   extracted a value : {n_ok}")
    print(f"[extract]   genuine 'none'    : {n_none}")
    print(f"[extract]   low confidence    : {n_lowconf}   (< theta {theta}; residual)")
    print(f"[extract]   JSON PARSE FAILS  : {n_parse_fail}   (incl. {n_error} call errors)")
    print(f"[extract]   meta -> {out_path}.meta.json")
    if n_parse_fail > len(attrs) * 0.3:
        print("[extract] >30% parse failures: the model may be too weak for strict JSON.")
    return meta
